INSERT INTO CARRERA (nombre,campus) values ('Ingeniería Civil','San Joaquin');
INSERT INTO CARRERA (nombre,campus) values ('Ingeniería Civil Eléctrica','San Joaquin');
INSERT INTO CARRERA (nombre,campus) values ('Ingeniería Civil Informática','San Joaquin');
INSERT INTO CARRERA (nombre,campus) values ('Ingeniería Civil Matemática','San Joaquin');
INSERT INTO CARRERA (nombre,campus) values ('Ingeniería Civil Mecánica','San Joaquin');
INSERT INTO CARRERA (nombre,campus) values ('Ingeniería Civil de Minas','San Joaquin');
INSERT INTO CARRERA (nombre,campus) values ('Ingeniería Civil Química','San Joaquin');
INSERT INTO CARRERA (nombre,campus) values ('Plan Común para Ingenierías y Licenciaturas','San Joaquin');
INSERT INTO CARRERA (nombre,campus) values ('Ingeniería Civil Industrial','Vitacura');
INSERT INTO CARRERA (nombre,campus) values ('Ingeniería Comercial','Vitacura');
INSERT INTO CARRERA (nombre,campus) values ('Ingeniería en Aviación Comercial','Vitacura');
INSERT INTO CARRERA (nombre,campus) values ('Piloto Comercial','Vitacura');
INSERT INTO CARRERA (nombre,campus) values ('Técnico Universitario en Mantenimiento Areonáutico','Vitacura');

INSERT INTO AREA (nombre,n_colaboradores,horario) values ('Coordinación General',0,'1-10');
INSERT INTO AREA (nombre,n_colaboradores,horario) values ('Túnel',0,'1-2');
INSERT INTO AREA (nombre,n_colaboradores,horario) values ('Dinámicas',0,'3-4');
INSERT INTO AREA (nombre,n_colaboradores,horario) values ('Concursos',0,'3-4');
INSERT INTO AREA (nombre,n_colaboradores,horario) values ('Alimentación',0,'5-8');
INSERT INTO AREA (nombre,n_colaboradores,horario) values ('Registro Visual',0,'1-10');
INSERT INTO AREA (nombre,n_colaboradores,horario) values ('Audio',0,'5-10');
